version: '3.8'

services:
  spring-boot-app:
    image: fii-practic-spring-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - flyway

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: fiipractic
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    command: --tls-version=''
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/migrations:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    command: migrate
    depends_on:
      - mysql

volumes:
  mysql-data:
