CREATE TABLE users (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    FOLLOWERS INT
);